### ISSUE TITLE
Questions about the map_func1 function in Warp() class.

### ISSUE THREAD

**Issue by jry01** [Eskender-B/roi-tanh#2]
Hi Eskender,
Thanks for your work! I was reading your code and had some questions about the [map_func1](https://github.com/Eskender-B/roi-tanh/blob/71375ccceec020a847c31f9e3599803e6f1ec44d/preprocess.py#L72) function. 
Why is "tform2 = transform.SimilarityTransform(scale=1./257., rotation=0, translation=(-0.99, -0.99))" needed after transforming five detected landmarks to match five predefined template points?
Thank you!

**Comment by eskender-f** [comment]
in the next line archtanh takes coordinate values between -1 and 1. As the input image is 512 X 512 we need to translate and scale to bring the pixel coordinates in the range [-1,1]

**Comment by jry01** [comment]
I got it, thank you!
